import SmoothScroll from "@/components/SmoothScroll";
import "./globals.css";

import { Inter, JetBrains_Mono } from "next/font/google";
import LayoutWrapper from "@/components/LayoutWrapper"; // <-- Import unique wrapper

export const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-jetbrains-mono",
  display: "swap",
});

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${jetbrainsMono.variable} h-full antialiased`}
    >
      <body suppressHydrationWarning className="min-h-full bg-[#1e1412]"> {/* Pro-Tip: Match background color here to avoid screen flash */}
        <LayoutWrapper>
          <SmoothScroll>
            {children}
          </SmoothScroll>
        </LayoutWrapper>
      </body>
    </html>
  );
}